name: Docker Publish

on:
  push:
    branches: ["development"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.1'

    - name: Install php dependencies
      run: composer install
      
    - name: Install node dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: docker-compose up --build

    # - name: Install PHP dependencies for testing
    #   run: docker-compose run app composer install

    - name: Create database table for testing
      run: |
        docker-compose run app php artisan migrate --database=mysql_testing
        docker-compose run app php artisan db:seed --class=DummyContentSeeder --database=mysql_testing
      continue-on-error: true
      
    - name: Run tests
      run: docker-compose run app php vendor/bin/phpunit

    - name: Shutdown Docker
      run: docker-compose down
